
language: c

#ubuntu 14.04
dist: trusty
sudo: false

os:
  - linux

before_install:
# download the Renesas RX gcc compiler file
  - wget -O gcc_rx.tar.xz https://github.com/GerryFerdinandus/Renesas-RX-GCC/releases/download/V4.8.0.201603/gcc_rx.tar.xz

install:
# extract the gcc compiler to folder prefix
  - mkdir prefix
  - tar -xvf gcc_rx.tar.xz -C prefix --strip-components 1

script:
# Export path to the gcc compiler in folder prefix
  - export PATH="$PWD/prefix/bin:$PATH"
# Show the GCC version
  - rx-elf-gcc --version
# Start building the program
  - make clean
  - make

# No need to get all the GIT history
git:
  depth: 1
